
global:
  scrape_interval: 15s #Default scraping interval is 15 seconds if not specified.

scrape_configs:
  #Targetting itself, to make sure it's okay
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
